### PR TITLE
Upgrade to .Net 6.0

### PR DESCRIPTION
**Pull request by dlahmad**
Hi everyone,

could we upgrade this NuGet to .Net 6.0 with the changes proposed here?

Best regards
Stephen

### CODE REVIEW

**Comment by johnnyreilly** [comment]
From https://github.com/vitalybibikov/AzureExtensions.Swashbuckle/issues/95

It looks like this is an abandoned project unfortunately.

For whatever reason @vitalybibikov isn't maintaining this. No judgement on him, doing open source is a gift to the community and not an obligation.

It might be worth some folk forking the project if they'd like to keep using it. If not, then it's probably worth taking a look for alternatives.

**Comment by vitalybibikov** [comment]
@johnnyreilly Sorry, just migrated from Belarus to Ukraine, and after that I had to leave Ukraine to Poland, so for now I'm pretty much limited in time on OSS.

**Comment by vitalybibikov** [comment]
I'll merge this one, but for now I don't have even home computer, so I can't validate it.

**Comment by johnnyreilly** [comment]
Oh wow - that's rough. I hope you're okay. Would you like some help maintaining this project? If there's people who want to assist then maybe there's a way to share the burden? I say this an OSS maintainer that recognises that it can be difficult doing OSS when life is tough

**Pull request merged**
